services:
    fpm:
        build:
            context: .
            dockerfile: fpm.dockerfile
            args:
                # UID and GID must be set as environment variables on the host machine
                USER_ID: 1000
                GROUP_ID: 1000
        ports:
        - "8880:8080"
        environment:
            SSL_MODE: "off"
        volumes:
            - .:/var/www/html
    nginx-unit:
        build:
            context: .
            dockerfile: nginx-unit.dockerfile
            args:
                # UID and GID must be set as environment variables on the host machine
                USER_ID: 1000
                GROUP_ID: 1000
        ports:
            - "8881:8080"
        environment:
            SSL_MODE: "off"
        volumes:
            - .:/var/www/html
    octane:
        build:
            context: .
            dockerfile: octane.dockerfile
            args:
                # UID and GID must be set as environment variables on the host machine
                USER_ID: 1000
                GROUP_ID: 1000
        ports:
            - "8882:8080"
        environment:
            SSL_MODE: "off"
        volumes:
            - .:/var/www/html
